output "application_url" {
  value       = "https://${azurerm_linux_function_app.application.name}.azurewebsites.net"
  description = "The Azure Functions application URL."
}

output "application_caf_name" {
  value       = azurecaf_name.function_app.result
  description = "The application name generated by the Azure Cloud Adoption Framework."
}
