name: REST Server - Continuous Integration

###
# Continuous integration GitHub Action
#
# -> Push your code to the `main` branch to have it automatically tested
#
###

on:
  push:
    branches:
      - main
    paths:
      - 'rest-server/**'
      - '.github/workflows/rest-server-continuous-integration.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'rest-server/**'
      - '.github/workflows/rest-server-continuous-integration.yml'
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/rest-server
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 17
        check-latest: false
        cache: 'maven'
    - name: Run tests
      run: mvn verify
  build_java_docker_image:
    name: Build and publish a JVM-based Docker image
    needs: [ test ]
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: 'ghcr.io/microsoft/nubesgen/nubesgen'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Packages
        run: docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
          check-latest: false
          cache: 'maven'
      - name: Build the Docker image
        run: mvn spring-boot:build-image -Dspring-boot.build-image.imageName=${{ env.DOCKER_IMAGE_NAME }}:main -DskipTests
        working-directory: ${{ github.workspace }}/rest-server
      - name: Push to GitHub Packages
        run: docker push ${{ env.DOCKER_IMAGE_NAME }}:main
        if: ${{ github.repository == 'microsoft/nubesgen' && github.event_name != 'pull_request' }}
  build_native_docker_image:
    name: Build and publish a native (Linux) Docker image
    needs: [ test ]
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: 'ghcr.io/microsoft/nubesgen/nubesgen-native'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Packages
        run: docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
          check-latest: false
          cache: 'maven'
      - name: Build the Docker image
        run: mvn -Pnative spring-boot:build-image -Dspring-boot.build-image.imageName=${{ env.DOCKER_IMAGE_NAME }}:main -DskipTests
        working-directory: ${{ github.workspace }}/rest-server
      - name: Push to GitHub Packages
        run: docker push ${{ env.DOCKER_IMAGE_NAME }}:main
        if: ${{ github.repository == 'microsoft/nubesgen' && github.event_name != 'pull_request' }}
