name: REST Server - Create Infrastructure

###
# Create infrastructure GitHub Action
#
# See https://github.com/microsoft/NubesGen/blob/main/docs/gitops-overview.md 
# for more information about using GitOps with NubesGen.
###

on:
  create:
    branches:
      - 'env-*'
jobs:
  terraform:
    if: startsWith(github.ref, 'refs/heads/env-')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set environment variables
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      run: |
        TAG_NAME=${GITHUB_REF#refs/*/}
        echo "ENVIRONMENT_NAME=${TAG_NAME:4}" >> $GITHUB_ENV
        echo "ARM_CLIENT_ID=$(echo $AZURE_CREDENTIALS | jq -r .clientId)" >> $GITHUB_ENV
        echo "ARM_CLIENT_SECRET=$(echo $AZURE_CREDENTIALS | jq -r .clientSecret)" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=$(echo $AZURE_CREDENTIALS | jq -r .subscriptionId)" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=$(echo $AZURE_CREDENTIALS | jq -r .tenantId)" >> $GITHUB_ENV
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Initialize Terraform
      env:
        TF_STORAGE_ACCOUNT: ${{ secrets.TF_STORAGE_ACCOUNT }}
      run: |
        terraform init \
        -input=false \
        -backend-config="resource_group_name=rg-terraform-001" \
        -backend-config="storage_account_name=$TF_STORAGE_ACCOUNT" \
        -backend-config="container_name=tfstate" \
        -backend-config="key=$ENVIRONMENT_NAME.terraform.tfstate"
      working-directory: '${{ github.workspace }}/terraform'
    - name: Apply Terraform
      env:
        TF_STORAGE_ACCOUNT: ${{ secrets.TF_STORAGE_ACCOUNT }}
      run: |
        terraform apply \
        -input=false \
        -auto-approve \
        -backend-config="resource_group_name=rg-terraform-001" \
        -backend-config="storage_account_name=$TF_STORAGE_ACCOUNT" \
        -backend-config="container_name=tfstate" \
        -backend-config="key=$ENVIRONMENT_NAME.terraform.tfstate"
        -var="environment=$ENVIRONMENT_NAME"
      working-directory: '${{ github.workspace }}/rest-server/terraform'
