output "application_url" {
  value       = "https://${azurerm_app_service.application.default_site_hostname}"
  description = "The Web application URL."
}

output "application_fqdn" {
  value       = azurerm_app_service.application.default_site_hostname
  description = "The Web application ully qualified domain name (FQDN)."
}

output "application_caf_name" {
  value       = azurecaf_name.app_service.result
  description = "The application name generated by the Azure Cloud Adoption Framework."
}
