output "spring_cloud_service_name" {
  value       = local.spring_cloud_service_name
  description = "Azure Spring Cloud service name"
}

output "application_hostname" {
  value = azurerm_spring_cloud_app.application.url
}

output "application_caf_name" {
  value       = local.spring_cloud_app_name
  description = "The application name generated by the Azure Cloud Adoption Framework."
}
