output "application_hostname" {
  value       = "https://${azurerm_app_service.application.default_site_hostname}"
  description = "The Web application URL."
}

output "application_caf_name" {
  value       = azurecaf_name.app_service.result
  description = "The application name generated by the Azure Cloud Adoption Framework."
}
