name: REST Server - Pull Requests automatic tests

###
# GitHub Action for testing Pull Requests
#
# -> Submit a PR to have it automatically tested
#
###

on:
  pull_request:
    branches:
      - main
    paths:
      - 'rest-server/**'
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/rest-server
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 11
        check-latest: false
        cache: 'maven'
    - name: Run tests
      run: mvn verify
