name: REST Server - Continuous Deployment

###
# Continuous deployment GitHub Action
#
# -> Push your code to the `prod` branch to have it automatically deployed to production
#
# This needs the following env variable defined in GitHub secrets:
#
## AZURE_CREDENTIALS ##
# RESOURCE_ID=$(az group show --name "rg-nubesgen-001" --query id -o tsv)
# SPNAME="sp-$(az webapp list --resource-group rg-nubesgen-001  --query '[].name' -o tsv)"
# az ad sp create-for-rbac --name "${SPNAME}" --role contributor --scopes "$RESOURCE_ID" --sdk-auth
# -> copy this JSON data to the AZURE_CREDENTIALS GitHub secret
###

on:
  push:
    branches:
      - prod
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/rest-server
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
          check-latest: false
          cache: 'maven'
      - name: Build with Maven
        run: mvn package
      - name: Temporarily save package
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ github.workspace }}/rest-server/target/*.jar
          retention-days: 1
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: package
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
          app-name: nubesgen
          package: '*.jar'
