name: Web UI - Continuous Integration

###
# Continuous integration GitHub Action for the Web UI
###

on:
  push:
    branches:
      - '*'
    paths:
      - 'rest-server/src/main/resources/static/**'
      - '.github/workflows/web-ui-continuous-integration.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'rest-server/src/main/resources/static/**'
      - '.github/workflows/web-ui-continuous-integration.yml'
jobs:
  accessibility:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/rest-server
    steps:
    - uses: actions/checkout@v2
    - name: Scan for accessibility issues
      uses: microsoft/accessibility-insights-action@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        site-dir: ${{ github.workspace }}/rest-server/src/main/resources/static
    - name: Upload report artifact
      uses: actions/upload-artifact@v2
      with:
        name: accessibility-reports
        path: ${{ github.workspace }}/_accessibility-reports
