package io.github.nubesgen.configuration;

/**
 * Runtimes supported.
 * <p>
 * Those can also be grouped in the following categories:
 * <p>
 * DOCKER = DOCKER, DOCKER_SPRING, DOCKER_MICRONAUT, DOCKER_MICRONAUT_GRADLE, QUARKUS_NATIVE
 * JAVA = JAVA, JAVA_GRADLE, SPRING, SPRING_GRADLE, QUARKUS, MICRONAUT, MICRONAUT_GRADLE
 * SPRING = DOCKER_SPRING, SPRING, SPRING_GRADLE
 * MAVEN = DOCKER_SPRING, JAVA, SPRING, QUARKUS, QUARKUS_NATIVE, MICRONAUT, DOCKER_MICRONAUT
 * GRADLE = JAVA_GRADLE, SPRING_GRADLE, MICRONAUT_GRADLE, DOCKER_MICRONAUT_GRADLE
 * QUARKUS = QUARKUS, QUARKUS_NATIVE
 * MICRONAUT = DOCKER_MICRONAUT, DOCKER_MICRONAUT_GRADLE, MICRONAUT, MICRONAUT_GRADLE
 */
public enum RuntimeType {
    DOCKER,
    DOCKER_SPRING,
    DOCKER_MICRONAUT,
    DOCKER_MICRONAUT_GRADLE,
    JAVA,
    JAVA_GRADLE,
    SPRING,
    SPRING_GRADLE,
    QUARKUS,
    QUARKUS_NATIVE,
    MICRONAUT_GRADLE,
    MICRONAUT,
    DOTNET,
    NODEJS,
    PYTHON,
}
